openapi: 3.0.0
info:
  title: "UMC 7th Node.js"
  description: "UMC 7th Node.js 테스트 프로젝트"
  version: "1.0.0"
host: "localhost:3001"
path: {}
components: 
  schemas: 
    ErrorResponse: 
      type: "object"
      properties: 
        resultType: 
          type: "string"
          example: "FAIL"
        error: 
          type: "object"
          properties: 
            errorCode: 
              type: "string"
              example: "U404"
            reason:
              type: "string"
              example: "string"
            data: 
              type: "object"
              example: {}
        success:
          type: "object"
          nullable: true
          example: null