name: deploy-main

on:
    push:
        branches:
            - main # main 브랜치에 새로운 커밋이 올라왔을 때 실행되도록 한다.
    workflow_dispatch: # 필요한 경우 수동으로 실행할 수 있도록 한다.

jobs:
    deploy:
        runs-on: ubuntu-latest # CI/CD 파이프라인이 실행될 운영체제 환경을 지정한다. 
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Check prisma has changes # prisma 폴더의 파일의 변경사항이 있는지 검사한다.
              uses: dorny/paths-filter@v3
              id: paths-filter
              with:
                filters: |
                  prisma: ["prisma/**"]

            - name: Configure SSH
              run: |
                mkdir -p ~/.ssh
                echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

                cat >>~/.ssh/config <<END
                Host UMC-7th-Nodejs-Wenty
                    HostName $EC2_HOST
                    User $EC2_USER
                    IdentityFile ~/.ssh/id_rsa
                    StrictHostKeyChecking no
                END
              env:
                EC2_USER: ubuntu
                EC2_HOST: ${{ secrets.EC2_HOST }}
                EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
            
            - name: Copy Workspace
              run: |
                ssh UMC-7th-Nodejs-Wenty 'sudo mkdir -p /opt/app'
                ssh UMC-7th-Nodejs-Wenty 'sudo chown ubuntu:ubuntu /opt/app'
                scp -r ./[!.]* UMC-7th-Nodejs-Wenty:/opt/app
            
            - name: Install dependencies
              run: |
                ssh UMC-7th-Nodejs-Wenty 'cd /opt/app; npm install'
                ssh UMC-7th-Nodejs-Wenty 'cd /opt/app; npm exec prisma generate'

            - name: Apply prisma migrations # steps.paths-filter.outputs.prisma를 통해 prisma 폴더의 파일의 변경 사항이 있다면 EC2 서버에 추가적으로 DB Migrate를 실행한다. 
              if: steps.paths-filter.outputs.prisma == 'true' 
              run: |
                ssh UMC-7th-Nodejs-Wenty 'cd /opt/app; npm exec prisma migrate deploy'

            - name: Copy systemd service file
              run: | 
                ssh UMC-7th-Nodejs-Wenty '
                    echo "[Unit]
                    Description=UMC 7th Node.js Project
                    After=network.target
                    
                    [Service]
                    User=${USER}
                    ExecStart=/usr/bin/npm run start --prefix /opt/app/
                    Restart=always
                    
                    [Install]
                    WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service
                    '

            - name: Enable systemd service
              run: |
                ssh UMC-7th-Nodejs-Wenty 'sudo systemctl daemon-reload'
                ssh UMC-7th-Nodejs-Wenty 'sudo systemctl enable app'
            
            - name: Restart systemd service
              run: |
                ssh UMC-7th-Nodejs-Wenty 'sudo systemctl restart app'